# Generated by Django 2.1 on 2018-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalware', '0002_auto_20180905_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastener',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
